/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bug_tracing_system.Tester;

import bug_tracing_system.Data;
import bug_tracing_system.Name;
import bug_tracing_system.DataBase;
import bug_tracing_system.Users;
import bug_tracing_system.bugData;
import bug_tracing_system.Login.Login;
import java.awt.Frame;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.image.BufferedImage;
import javax.swing.table.DefaultTableModel;
import java.io.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.*;


/**
 *
 * @author Jimmy
 */
public class Tester extends javax.swing.JFrame implements Data, Name {
    static int xPress = 0;
    static int yPress = 0;
    private String projectName;
    private int bugId;
    private String bugName ;
    private String bugType ;
    private String priorty;
    private String statue;
    private String developerName;
    private String bugDes;
    private ImageIcon imageIcon;
    static Users myuser;
    ArrayList<bugData> arrLst = new ArrayList<>();
    TesterView testerView = new TesterView();

    /**
     * Creates new form Tester
     * @param user
     */
    public Tester(Users user) {
        initComponents();
        myuser = user;
        this.userName.setText(user.getName());
        DefaultTableModel model;
        model = (DefaultTableModel) bugsTable.getModel();
        
        Timer timer = new Timer(1000, (ActionEvent ae) -> {    
            try {
                model.setRowCount(0);
                getData();
                for (int i = 0; i < arrLst.size(); i++) {
                    bugData bug = arrLst.get(i);
                    Object Data[] = {bug.getProjectName(), bug.getBugId(), bug.getBugName(), bug.getBugType(), bug.getPriorty(), bug.getStatue(), getName(bug.getDeveloperId())}; //data added in table
                    model.addRow(Data);
                }
                arrLst = new ArrayList<>();
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(Tester.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
        timer.start();
    }
    

    @Override
    public String getName(int devId) throws SQLException, ClassNotFoundException {
        DataBase db = new DataBase();           
            String sql = "SELECT FName, LName FROM accounts WHERE UserId="+ devId;
            ResultSet rs = db.selectQuery(sql);
            while(rs.next())
               return rs.getString("FName") + " " + rs.getString("LName");    
        return "NOT FOUND";  
    }

    @Override
    public void getData() throws SQLException, ClassNotFoundException {  
        DataBase db = new DataBase();           
            String sql = "SELECT b.*, p.* FROM bugs as b, projects as p WHERE p.ProjectId=b.ProjectId and b.TesterId="+ myuser.getID();
            ResultSet rs = db.selectQuery(sql);
            while(rs.next())
            {
               bugData bug = new bugData(rs.getString(12),rs.getInt(8),rs.getInt(1), rs.getString(3), rs.getString(4), rs.getString(5),rs.getString(2), rs.getString(7), rs.getInt(9), rs.getString(6));
               arrLst.add(bug);
            } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        reportBugBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        minimizeBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bugsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(33, 63, 86));

        jLabel1.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome");

        userName.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        userName.setForeground(new java.awt.Color(255, 255, 255));
        userName.setText("jLabel2");

        reportBugBtn.setBackground(new java.awt.Color(204, 204, 204));
        reportBugBtn.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        reportBugBtn.setForeground(new java.awt.Color(33, 63, 86));
        reportBugBtn.setText("Report a bug");
        reportBugBtn.setBorder(null);
        reportBugBtn.setFocusPainted(false);
        reportBugBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportBugBtnActionPerformed(evt);
            }
        });

        logoutBtn.setBackground(new java.awt.Color(33, 63, 86));
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-logout-50_2.png"))); // NOI18N
        logoutBtn.setToolTipText("Logout");
        logoutBtn.setBorder(null);
        logoutBtn.setFocusPainted(false);
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(userName))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(reportBugBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(reportBugBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(logoutBtn)
                .addGap(46, 46, 46))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tester Dashboard");

        minimizeBtn.setBackground(new java.awt.Color(0, 153, 153));
        minimizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-minimize-window-40.png"))); // NOI18N
        minimizeBtn.setToolTipText("Logout");
        minimizeBtn.setBorder(null);
        minimizeBtn.setBorderPainted(false);
        minimizeBtn.setFocusPainted(false);
        minimizeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeBtnActionPerformed(evt);
            }
        });

        closeBtn.setBackground(new java.awt.Color(0, 153, 153));
        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_close_window_40px.png"))); // NOI18N
        closeBtn.setToolTipText("Logout");
        closeBtn.setBorder(null);
        closeBtn.setBorderPainted(false);
        closeBtn.setFocusPainted(false);
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimizeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeBtn))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minimizeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addGap(23, 23, 23))
        );

        bugsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProjectName", "BugId", "BugName", "BugType", "Priority", "Status", "DevName"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bugsTable.getTableHeader().setReorderingAllowed(false);
        bugsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bugsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bugsTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bugsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bugsTableMouseClicked
        try {
            readData();
            openBugDetails();
            setBugDetails();
        } catch (IOException | NumberFormatException ex) {
             JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Tester.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bugsTableMouseClicked

    private void openBugDetails() throws NumberFormatException {     
        testerView.setVisible(true);
        testerView.pack();
        testerView.setLocationRelativeTo(null);
        testerView.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
    }

    private void setBugDetails() {
        testerView.developerText.setText(developerName);
        testerView.projectNameText.setText(projectName);
        testerView.bugNameText.setText(bugName);
        testerView.bugTypeText.setText(bugType);
        testerView.priortyText.setText(priorty);
        testerView.statueText.setText(statue);
        testerView.pic1.setIcon(imageIcon);
        testerView.bugDesText.setText(bugDes);
    }

    private void readData() throws NumberFormatException, IOException, SQLException, ClassNotFoundException {
        DefaultTableModel model;
        model = (DefaultTableModel) bugsTable.getModel();
        int index = bugsTable.getSelectedRow();
        projectName = model.getValueAt(index, 0).toString();
        bugId = Integer.parseInt(model.getValueAt(index, 1).toString());
        bugName = model.getValueAt(index, 2).toString();
        bugType = model.getValueAt(index, 3).toString();
        priorty = model.getValueAt(index, 4).toString();
        statue = model.getValueAt(index, 5).toString();
        developerName = model.getValueAt(index, 6).toString();
        
        BufferedImage img = null;
        img = ImageIO.read(new File("imgs\\" + bugId + ".png"));
        Image dimg = img.getScaledInstance(832, 355, Image.SCALE_SMOOTH);
        imageIcon = new ImageIcon(dimg);
        
        DataBase db = new DataBase();
        String sql = "SELECT BugDetails FROM bugs WHERE BugId = " +  bugId;
        ResultSet rs = db.selectQuery(sql);
        while(rs.next())
            bugDes = rs.getString("BugDetails");
    }

    private void reportBugBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportBugBtnActionPerformed
        BugSubmiter addBug = new BugSubmiter(myuser);
        addBug.setVisible(true);
        addBug.pack();
        addBug.setLocationRelativeTo(null);
        addBug.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_reportBugBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Are you sure you want to logout", "LOGOUT ?",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
        this.dispose();
        new Login().setVisible(true);
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void minimizeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeBtnActionPerformed
        setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minimizeBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Are you sure you want to close the program?", "EXIT?",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
        System.exit(0);
        }
    }//GEN-LAST:event_closeBtnActionPerformed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        setLocation(evt.getXOnScreen()-xPress,evt.getYOnScreen()-yPress);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
         xPress = evt.getX();
        yPress = evt.getY();
    }//GEN-LAST:event_formMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Tester(myuser).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable bugsTable;
    private javax.swing.JButton closeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton minimizeBtn;
    private javax.swing.JButton reportBugBtn;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
